# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170115_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(default='post_covers/stock-cover.jpg', upload_to='post_covers'),
        ),
    ]
