# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_auto_20170205_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmhwprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AddField(
            model_name='nmhwprofile',
            name='resume',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='nmhwprofile',
            name='description',
            field=redactor.fields.RedactorField(verbose_name='description'),
        ),
    ]
