# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_auto_20170205_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmhwprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='nmhwprofile',
            name='resume',
            field=models.URLField(blank=True, default=''),
        ),
    ]
