# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='image_%m_%d_%Y_%H%M%S')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2048)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
