# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_img', models.ImageField(default='', upload_to='project_covers')),
                ('body', models.TextField()),
                ('code', models.TextField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('private', 'Private')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
