# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170610_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_img',
            field=models.ImageField(default='post_covers/stock-cover.jpg', upload_to='project_covers'),
        ),
    ]
