# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170610_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='project_data', validators=[projects.models.validate_data_file_extension]),
        ),
    ]
