# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170610_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
        migrations.AlterModelOptions(
            name='scripts',
            options={'verbose_name_plural': 'scripts'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scripts',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='data_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Data'),
        ),
        migrations.AddField(
            model_name='project',
            name='scripts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Scripts'),
        ),
    ]
