# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170611_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='data_sets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scripts',
        ),
        migrations.AddField(
            model_name='data',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='scripts',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='projects.Project'),
        ),
    ]
