# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180131_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scripts',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='data_sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Data'),
        ),
        migrations.AddField(
            model_name='project',
            name='scripts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Scripts'),
        ),
    ]
